#############################################################################
# Makefile for building: release/menu
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  menu.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile menu.pro -spec linux-g++-64 'CONFIG-=debug release debug_and_release' CONFIG+=release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_NO_DEBUG -DREV_SUBVN_CODE=124 -DREV_SUBVN_DATE=\"\" -DREV_SUBVN_HOUR=\"\" -DREV_PATCH_CODE=0 -DREV_MINOR_CODE=8 -DREV_MAJOR_CODE=0 -DREV_CODE=\"0.8.0.124\" -DAPP_VERSION=\"0.8.0.124\" -DAPP_NAME=\"menu\" -DARCH_x86_64 -D_LINUX -DQT_DLL -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O3 -mtune=native -march=native -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipe -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipeB -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O3 -mtune=native -march=native -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipe -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipe -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/run/user/1000/menu/GeneratedFiles -I. -I/run/user/1000/menu/GeneratedFiles/release -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I/run/user/1000/menu/GeneratedFiles -I/run/user/1000/menu/GeneratedFiles -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = menu1.0.0
DISTDIR = /run/user/1000/menu/GeneratedFiles/release/menu1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 /usr/lib/x86_64-linux-gnu/libQt5Svg.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = /run/user/1000/menu/GeneratedFiles/release/

####### Files

SOURCES       = main.cpp \
		CGMenu.cpp \
		CTelaConfirmacao.cpp \
		CQuickMenu.cpp \
		CQuickMenuLineEdit.cpp /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp \
		/run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp \
		/run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp \
		/run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp \
		/run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp \
		/run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp
OBJECTS       = /run/user/1000/menu/GeneratedFiles/release/main.o \
		/run/user/1000/menu/GeneratedFiles/release/CGMenu.o \
		/run/user/1000/menu/GeneratedFiles/release/CTelaConfirmacao.o \
		/run/user/1000/menu/GeneratedFiles/release/CQuickMenu.o \
		/run/user/1000/menu/GeneratedFiles/release/CQuickMenuLineEdit.o \
		/run/user/1000/menu/GeneratedFiles/release/qrc_CGMenu.o \
		/run/user/1000/menu/GeneratedFiles/release/qrc_CGMenuJPEG.o \
		/run/user/1000/menu/GeneratedFiles/release/moc_CGMenu.o \
		/run/user/1000/menu/GeneratedFiles/release/moc_CTelaConfirmacao.o \
		/run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenu.o \
		/run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenuLineEdit.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../QtBaseGeral/base_geral.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		menu.pro CGMenu.h \
		CTelaConfirmacao.h \
		CQuickMenu.h \
		CQuickMenuLineEdit.h main.cpp \
		CGMenu.cpp \
		CTelaConfirmacao.cpp \
		CQuickMenu.cpp \
		CQuickMenuLineEdit.cpp
QMAKE_TARGET  = menu
DESTDIR       = release/
TARGET        = release/menu


first: all
####### Build rules

release/menu: /run/user/1000/menu/GeneratedFiles/ui_CGMenu.h /run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h /run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h $(OBJECTS)  
	@test -d release/ || mkdir -p release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: menu.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../QtBaseGeral/base_geral.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		menu.pro \
		CGMenu.qrc \
		CGMenuJPEG.qrc
	$(QMAKE) -o Makefile menu.pro -spec linux-g++-64 'CONFIG-=debug release debug_and_release' CONFIG+=release
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
../QtBaseGeral/base_geral.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
menu.pro:
CGMenu.qrc:
CGMenuJPEG.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile menu.pro -spec linux-g++-64 'CONFIG-=debug release debug_and_release' CONFIG+=release

qmake_all: FORCE


all: Makefile release/menu

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents CGMenu.qrc CGMenuJPEG.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CGMenu.h CTelaConfirmacao.h CQuickMenu.h CQuickMenuLineEdit.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp CGMenu.cpp CTelaConfirmacao.cpp CQuickMenu.cpp CQuickMenuLineEdit.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CGMenu.ui CTelaConfirmacao.ui CQuickMenu.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp /run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp
compiler_rcc_clean:
	-$(DEL_FILE) /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp /run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp
/run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp: CGMenu.qrc \
		/usr/lib/qt5/bin/rcc \
		../iView/recursos/imagens/Seta_06_E.svg \
		../iView/recursos/imagens/Seta_01_NOdesl.svg \
		../iView/recursos/imagens/swiss\ knife.svg \
		../iView/recursos/imagens/Movimento_Automatico.svg \
		../iView/recursos/imagens/Seta_03_NE.svg \
		../iView/recursos/imagens/ObjetivaZoomMenosDesl.svg \
		resources/FundoMenuPrincipal.svg \
		../iView/recursos/imagens/Seta_03_NEdesl.svg \
		../iView/recursos/imagens/Imagem_ModoCaptura.svg \
		../iView/recursos/imagens/Movimento_ProgramadoCancelaDesl.svg \
		../iView/recursos/imagens/Seta_07_SOdesl.svg \
		resources/FundoMenuConfig.svg \
		../iView/recursos/imagens/Imagem_ModoCapturaDesl.svg \
		../iView/recursos/imagens/Movimento_ProgramadoOkDesl.svg \
		../iView/recursos/imagens/Menu.svg \
		../iView/recursos/imagens/ObjetivaIrisMenosDesl.svg \
		../iView/recursos/imagens/ObjetivaZoomMenos.svg \
		../iView/recursos/imagens/Seta_04_Odesl.svg \
		../iView/recursos/imagens/Seta_09_SE.svg \
		../iView/recursos/imagens/Imagem_Espelho.svg \
		../iView/recursos/imagens/ObjetivaIrisMais.svg \
		../iView/recursos/imagens/Imagem_DivisaoDesl.svg \
		../iView/recursos/imagens/Movimento_ProgramadoAndaParaDesl.svg \
		../iView/recursos/imagens/Movimento_ProgramadoOk.svg \
		../iView/recursos/imagens/Seta_09_SEdesl.svg \
		../iView/recursos/imagens/Seta_04_O.svg \
		../iView/recursos/imagens/camera.svg \
		../iView/recursos/imagens/Imagem_TrocaCameraDesl.svg \
		../iView/recursos/imagens/lens.svg \
		../iView/recursos/imagens/Imagem_TrocaCamera.svg \
		../iView/recursos/imagens/Imagem_ZoomDigitalDesl.svg \
		../iView/recursos/imagens/ObjetivaZoomMais.svg \
		../iView/recursos/imagens/ObjetivaFocoLongeDesl.svg \
		../iView/recursos/imagens/Seta_01_NO.svg \
		../iView/recursos/imagens/ProgramadoDesl.svg \
		../iView/recursos/imagens/ObjetivaFocoPertoDesl.svg \
		resources/FundoTelaConfirmacao.svg \
		../iView/recursos/imagens/RegistroDesl.svg \
		../iView/recursos/imagens/tools.svg \
		../iView/recursos/imagens/Programado.svg \
		../iView/recursos/imagens/Movimento_ProgramadoAndaPara.svg \
		../iView/recursos/imagens/Seta_08_S.svg \
		../iView/recursos/imagens/Imagem_ExtremosZoomDesl.svg \
		../iView/recursos/imagens/Seta_02_Ndesl.svg \
		../iView/recursos/imagens/Seta_07_SO.svg \
		../iView/recursos/imagens/Registro.svg \
		../iView/recursos/imagens/MenuDesl.svg \
		../iView/recursos/imagens/Desligar.svg \
		../iView/recursos/imagens/ObjetivaIrisMaisDesl.svg \
		../iView/recursos/imagens/Imagem_ZoomDigital.svg \
		../iView/recursos/imagens/Imagem_EspelhoDesl.svg \
		../iView/recursos/imagens/Movimento_AutomaticoDesl.svg \
		../iView/recursos/imagens/Movimento_ProgramadoCancela.svg \
		../iView/recursos/imagens/Seta_08_Sdesl.svg \
		../iView/recursos/imagens/icon.svg \
		resources/FundoTelaMenu.svg \
		../iView/recursos/imagens/Seta_06_Edesl.svg \
		../iView/recursos/imagens/ImagemRotacionarDesl.svg \
		../iView/recursos/imagens/ImagemRotacionar.svg \
		../iView/recursos/imagens/tela.svg \
		../iView/recursos/imagens/Imagem_ExtremosZoom.svg \
		../iView/recursos/imagens/ObjetivaIrisMenos.svg \
		../iView/recursos/imagens/ObjetivaFocoLonge.svg \
		../iView/recursos/imagens/Seta_02_N.svg \
		../iView/recursos/imagens/ObjetivaFocoPerto.svg \
		../iView/recursos/imagens/Imagem_Divisao.svg \
		../iView/recursos/imagens/ObjetivaZoomMaisDesl.svg \
		../iView/recursos/imagens/settings.svg
	/usr/lib/qt5/bin/rcc -name CGMenu CGMenu.qrc -o /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp

/run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp: CGMenuJPEG.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/Earth-Map_5.jpg \
		resources/flexible-packaging_0.jpg \
		resources/flexible-packaging_1.jpg \
		resources/flexible-packaging_2.jpg \
		resources/flexible-packaging_3.jpg \
		resources/flexible-packaging_4.jpg \
		resources/flexible-packaging_5.jpg \
		resources/Earth-Map_0.jpg \
		resources/Earth-Map_1.jpg \
		resources/Earth-Map_2.jpg \
		resources/Earth-Map_3.jpg \
		resources/Earth-Map_4.jpg
	/usr/lib/qt5/bin/rcc -name CGMenuJPEG CGMenuJPEG.qrc -o /run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp

compiler_moc_predefs_make_all: /run/user/1000/menu/GeneratedFiles/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) /run/user/1000/menu/GeneratedFiles/moc_predefs.h
/run/user/1000/menu/GeneratedFiles/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -O3 -mtune=native -march=native -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipe -mfpmath=sse -momit-leaf-frame-pointer -msahf -mcx16 -pipe -Wall -W -dM -E -o /run/user/1000/menu/GeneratedFiles/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: /run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp /run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp /run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp /run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) /run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp /run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp /run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp /run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp
/run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp: CGMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CGMenu.h \
		/run/user/1000/menu/GeneratedFiles/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /run/user/1000/menu/GeneratedFiles/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles/release -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CGMenu.h -o /run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp

/run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp: CTelaConfirmacao.h \
		/run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h \
		/run/user/1000/menu/GeneratedFiles/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /run/user/1000/menu/GeneratedFiles/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles/release -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CTelaConfirmacao.h -o /run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp

/run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp: CQuickMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h \
		CQuickMenuLineEdit.h \
		/run/user/1000/menu/GeneratedFiles/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /run/user/1000/menu/GeneratedFiles/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles/release -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CQuickMenu.h -o /run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp

/run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp: CQuickMenuLineEdit.h \
		/run/user/1000/menu/GeneratedFiles/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /run/user/1000/menu/GeneratedFiles/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles -I/home/francisco.ares/workspace/trunk/Francisco/menu -I/run/user/1000/menu/GeneratedFiles/release -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CQuickMenuLineEdit.h -o /run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: /run/user/1000/menu/GeneratedFiles/ui_CGMenu.h /run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h /run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h
compiler_uic_clean:
	-$(DEL_FILE) /run/user/1000/menu/GeneratedFiles/ui_CGMenu.h /run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h /run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h
/run/user/1000/menu/GeneratedFiles/ui_CGMenu.h: CGMenu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CGMenu.ui -o /run/user/1000/menu/GeneratedFiles/ui_CGMenu.h

/run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h: CTelaConfirmacao.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CTelaConfirmacao.ui -o /run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h

/run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h: CQuickMenu.ui \
		/usr/lib/qt5/bin/uic \
		CQuickMenuLineEdit.h
	/usr/lib/qt5/bin/uic CQuickMenu.ui -o /run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

/run/user/1000/menu/GeneratedFiles/release/main.o: main.cpp CGMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CGMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/main.o main.cpp

/run/user/1000/menu/GeneratedFiles/release/CGMenu.o: CGMenu.cpp CGMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CGMenu.h \
		CTelaConfirmacao.h \
		/run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h \
		CQuickMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h \
		CQuickMenuLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/CGMenu.o CGMenu.cpp

/run/user/1000/menu/GeneratedFiles/release/CTelaConfirmacao.o: CTelaConfirmacao.cpp CTelaConfirmacao.h \
		/run/user/1000/menu/GeneratedFiles/ui_CTelaConfirmacao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/CTelaConfirmacao.o CTelaConfirmacao.cpp

/run/user/1000/menu/GeneratedFiles/release/CQuickMenu.o: CQuickMenu.cpp CQuickMenu.h \
		/run/user/1000/menu/GeneratedFiles/ui_CQuickMenu.h \
		CQuickMenuLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/CQuickMenu.o CQuickMenu.cpp

/run/user/1000/menu/GeneratedFiles/release/CQuickMenuLineEdit.o: CQuickMenuLineEdit.cpp CQuickMenuLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/CQuickMenuLineEdit.o CQuickMenuLineEdit.cpp

/run/user/1000/menu/GeneratedFiles/release/qrc_CGMenu.o: /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/qrc_CGMenu.o /run/user/1000/menu/GeneratedFiles/qrc_CGMenu.cpp

/run/user/1000/menu/GeneratedFiles/release/qrc_CGMenuJPEG.o: /run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/qrc_CGMenuJPEG.o /run/user/1000/menu/GeneratedFiles/qrc_CGMenuJPEG.cpp

/run/user/1000/menu/GeneratedFiles/release/moc_CGMenu.o: /run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/moc_CGMenu.o /run/user/1000/menu/GeneratedFiles/moc_CGMenu.cpp

/run/user/1000/menu/GeneratedFiles/release/moc_CTelaConfirmacao.o: /run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/moc_CTelaConfirmacao.o /run/user/1000/menu/GeneratedFiles/moc_CTelaConfirmacao.cpp

/run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenu.o: /run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenu.o /run/user/1000/menu/GeneratedFiles/moc_CQuickMenu.cpp

/run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenuLineEdit.o: /run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /run/user/1000/menu/GeneratedFiles/release/moc_CQuickMenuLineEdit.o /run/user/1000/menu/GeneratedFiles/moc_CQuickMenuLineEdit.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

